name: publish
on: 
  push:
    branches:
      - main
  # workflow_dispatch:
  #   inputs:
  #     tag:
  #       type: string
  #       description: The tag to publish
  #       required: true

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Login to GitHub Container Registry
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build Docker image
        run: |
              docker build . --tag ghcr.io/balonmanovetusta/handball-liveshow-spain:latest
              docker run ghcr.io/balonmanovetusta/handball-liveshow-spain:latest
              docker push ghcr.io/balonmanovetusta/handball-liveshow-spain:latest