name: publish
on:
  push:
    paths:
      - "package.json"
      - "package-lock.json"
      - "Dockerfile"
      - "src/**"
      - "cfg/**"
      - "images/**"
      - "schemas/**"
      - ".github/workflows/publish.yml"
    branches:
      - main
  # workflow_dispatch:
  #   inputs:
  #     tag:
  #       type: string
  #       description: The tag to publish
  #       required: true

jobs:
  publish-docker-image:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET_PLATFORM: linux/amd64
      # DOCKER_TARGET_PLATFORM: linux/amd64,linux/arm64
    steps:
      - name: Login to GitHub Container Registry
        uses: actions/checkout@v2
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      #   with:
      #     platforms: "arm64,amd64"
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-nodecg-modules-
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Run NPM install
        run: npm install

      - name: Run NPM build
        run: npm run build

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/balonmanovetusta/handball-liveshow-spain:latest
